### ISSUE TITLE
cutting board requires enderite shears

### ISSUE THREAD

**Issue by toruPuchuu** [newhoryzon/farmers-delight-fabric#1]
I have "Enderite Mod" installed alongside Farmer's Delight (Fabric), and all of the Cutting Board shear recipes require enderite shears instead of also allowing iron shears to work.

Windows 10
Minecraft Java 1.19
Java 17.0.3 64bit
Fabric 0.14.8-1.19
Farmers Delight V1.19-0.3.0
Enderite Mod v1.4.1

**Comment by toruPuchuu** [comment]
This is a bug report. I mean iron shears no longer work in the cutting board. When I try to cut leather pants with iron shears, it says, "Maybe with a different tool..." Only enderite shears work for all cutting board+shears recipes.

**Comment by beaucoralk** [comment]
Ok I will not understand it well, thanks to complete and add precision for me. I label it as bug. Thanks you again.

**Comment by JieningYu** [comment]
the issue seems to be that the tag `#fabric:shears` is not defined in this mod but Enderite mod adds it.

**Comment by beaucoralk** [comment]
Yeah you right @JieningYu it's for sure because before 1.19/1.18 version of Fabric, it was the `fabric:shears` that was used, but not all common tag is using the `c` identifier for all common tag, so it will be updated #18.
