### ISSUE TITLE
[1.19.2] Missing translation for advancement title and description

### ISSUE THREAD

**Issue by 0rc1nus** [newhoryzon/farmers-delight-fabric#102]
Some of the advancements are not fully translated yet

i.e.
**Title**
"farmersdelight.advancement.place_stove"
"farmersdelight.advancement.drink_hot_cocoa"

**Description**
"farmersdelight.advancement.place_stove.desc"
"farmersdelight.advancement.drink_hot_cocoa.desc"

**Comment by Zifiv** [comment]
Hello @0rc1nus,

Thank you for the report.
These two advancement have been removed on last version of Farmer's Delight on forge, but I forgot to remove the advancement data file.
