### ISSUE TITLE
1.19.2 observer and hoppers not working with cutting board

### ISSUE THREAD

**Issue by Bladeract** [newhoryzon/farmers-delight-fabric#108]
I was playing with Farmer's Delight and Create, however, I can't get an observer, hopper, or comparator to register the cutting board as an inventory or updatable entity. Any suggestions?
Using Farmer's Delight 1.19.2-1.3.7

**Comment by Zifiv** [comment]
Hello @Bladeract,

Have you Lithium installed too (I guess it's a modpack). There is a known incompatibility with Lithium that I'm currently working on to fix with the issue #104.
An update will be available soon :) !

**Comment by Bladeract** [comment]
I don't have Lithium installed, my mod pack is rather small, It includes;
Architectury - 6.3.56
Cloth-Config - 8.2.88
Create-Fabric - 0.5.0g
Fabric-API - 0.67.1
Farmer's Delight - 1.3.7
Roughly Enough Items - 9.1.572

**Comment by Bladeract** [comment]
![Screenshot (3)](https://user-images.githubusercontent.com/83568248/204156572-849f4947-9a09-40a6-8e59-c325c6f96f13.png)

**Comment by Zifiv** [comment]
Can you update to lastest version of Famer's Delight fabric (1.3.9) and tell me if it continue not working.

**Comment by Bladeract** [comment]
I updated and encountered the same issue

**Comment by Bladeract** [comment]
I will await the new version with the fix, and I wish you the best of luck. I know how painful these kinds of fixes can be. One of my friends and I had worked on a mod once, but we never could get it to work correctly so we scraped it.

**Comment by Zifiv** [comment]
Thank you, the fix is already done for Cooking Pot and Cutting Board, it's will be ok for next release during the next week ;) !

**Comment by Bladeract** [comment]
You're a beautiful human being, thank you so much!

**Comment by StunnerPony** [comment]
Hello, sorry for reviving this thread, but is there any plans to fix this for 1.18.2?
I'm noticing the same issue on version 1.2.5 irregardless of lithium being installed or not.

Either way, thanks for all the work on this mod 🙏
