### ISSUE TITLE
Rice Crop has different block ids compared to Forge

### ISSUE THREAD

**Issue by blu3potato** [newhoryzon/farmers-delight-fabric#110]
The rice crops have different block ids, with Forge being named "rice" and "rice_panicle", while Fabric has "rice_crop" and "rice_upper_crop", respectively.
Other differences is that the the lower rice crop takes takes a bit longer to break to prevent accidental breaking when harvesting the upper panicles part of the block, as well as attempting to plant Rice above water doesn't display the hint message, leaving "block.rice.invalid_placement" unused.

**Comment by Zifiv** [comment]
Thanks for reporting this issue @blu3potato, added to the next release.
