### ISSUE TITLE
Other small bugs

### ISSUE THREAD

**Issue by blu3potato** [newhoryzon/farmers-delight-fabric#111]
- Melon Popsicle doesn't extinguish the player after eating.
- Cutting Board doesn't utilize the "#offhand_equipment" tag to prevent accidentally placing down the Shield when using it.
- Canvas Rug displays the breaking animation, but also shows on the 4 extrusions at the side making it look weird. In Forge the breaking animation doesn't show to prevent this.
- Wild Crops used to make Suspicious Stews doesn't grant any Status Effects when consumed.

**Comment by Zifiv** [comment]
Hello @blu3potato,

Thanks for reporting all this bugs.
It's better to create a new issue for each bugsn so this is what I'll do.
