### ISSUE TITLE
How can Backstabbing books be acquired in v1.3.9?

### ISSUE THREAD

**Issue by gniftygnome** [newhoryzon/farmers-delight-fabric#112]
I am pretty sure we were getting Backstabbing books in fishing loot in v1.3.5 (I can check this if you want) but we do not seem to be getting them in v1.3.9.  From a quick read of the source and data, I don't see any other way to get them in Survival.

This could just be me missing something obvious; if so I apologize.

P.S. they seem like a reasonable rare loot table entry for shipwrecks and dungeons, to me...

**Comment by Zifiv** [comment]
Hello @gniftygnome,

Backstabbing can be acquired by using enchanting table with a books. Backstabbing is only applyable on knives, so it's useless to have the books, you can easily have it on your knife on the enchanting table.

About the fishing loot, I think that all enchanted books can be fishing, it's only about your chance I guess.

**Comment by gniftygnome** [comment]
Ahh, I forgot about the enchanting table, because it is largely useless for technical play.

I was incorrect about getting Backstabbing books in earlier versions.  I do not believe you will ever get a Backstabbing book from fishing.  I checked both our 1.19.2 games and out of a sample of nearly 1k books, none were Backstabbing.  There were however a fair number of Magna's Curse of Gigantism books (which are another modded rare treasure enchantment).  So it still seems to me there is something not quite right about how the Backstabbing enchantment is registered with the game.

As a quick, uneducated guess, one or both of the following two additions to Farmer's Delight's enchantment definition for Backstabbing might do the trick:

```java
    @Override
    protected boolean canAccept(Enchantment other) {
        return other == Enchantments.SHARPNESS;
    }

    @Override
    public boolean isTreasure() {
        return true;
    }
```
