### ISSUE TITLE
[Bug] Stacked Mushrooom Soups disappear when you eat one soup - Fabric 1.19.2

### ISSUE THREAD

**Issue by xR4YM0ND** [newhoryzon/farmers-delight-fabric#118]
A stack or some soups act like 1 soup.
If you have more than one in a stack and eat, the rest is gone forever

**Comment by wefcdse** [comment]
so is the rabbit stew

**Comment by IdrisQe** [comment]
This is also an issue with 1.2.5 for 1.18.2, specifically any vanilla stew or soup which normally only stacks to 1

**Comment by SpigotDE** [comment]
same for buckets when you have eg. 16 buckets and you fill one with water, all others are gone

**Comment by Linguardium** [comment]
requires the rest of the StewItem mixin as seen in the Forge version https://github.com/vectorwing/FarmersDelight/blob/bdbdfb8dcc2a58b9796f1fe01b6ccbe383e9cb72/src/main/java/vectorwing/farmersdelight/common/mixin/SoupItemMixin.java#L43C5-L81

**Comment by Zifiv** [comment]
Hello there,

Thanks you for reporting this issue.

An issue/PR has been accepted and fixed this issue, it will be added in next release (#142 and for the pr #146).
