### ISSUE TITLE
Skillet Animation Bug

### ISSUE THREAD

**Issue by superbungus** [newhoryzon/farmers-delight-fabric#125]
Very Minor Nitpicking, but its a problem with the raw beefI have in offhand. It does not show in the skillet when holding right click over a heat source. Instead it disappears and reappears cooked.

**Comment by behindmatt** [comment]
I have encountered the same error, I'll try removing sodium and some other mods but I'm not sure what causes the bug.

**Comment by Zifiv** [comment]
Hello @superbungus,

Thanks you for reporting this issue.
The visual feature of skillet isn't already implemented, I've some trouble to add it actualy and like you said, it is a minor issue, so for not isn't my priority.
An issue is already created, you can check it if you want know the advancement of the feature : #41.
