### ISSUE TITLE
Trying to open Chocolate Pie Filling by Spout recipe with JEI crashes the game

### ISSUE THREAD

**Issue by lgowen22** [newhoryzon/farmers-delight-fabric#128]
Using Create Mod + Farmer's Delight + JEI, clicking on the recipe using Spouts to make Chocolate Pie crashed my game.

**Comment by Zifiv** [comment]
Hello @lgowen22,

The fabric hasn't a compatibility with JEI, it's compatible with REI.

**Comment by Zifiv** [comment]
Should be a duplicate of #115.
