### ISSUE TITLE
Farm Improvement (Villager Improvements)

### ISSUE THREAD

**Issue by WDGaster17** [newhoryzon/farmers-delight-fabric#129]
# Read please
make the villager that can plant because I already made a big farm and I put a villager but they don't plant the plants

**Comment by Zifiv** [comment]
Hello @WDGaster17,

Thanks you for reporting an idea to improve the experience of Farmer's Delight, but the fabric port does not add new feature that is not present in the original forge mod.

If you have any idea and want to be added, feel free to ask it on the forge mod issue tracker : https://github.com/vectorwing/FarmersDelight/issues.
