### ISSUE TITLE
[Suggestion] Netherite knife shouldn't burn in fire

### ISSUE THREAD

**Issue by xlifi** [newhoryzon/farmers-delight-fabric#147]
Currently netherite knife can burn down in fire. Any other netherite tool can not
![ezgif com-crop](https://github.com/newhoryzon/farmers-delight-fabric/assets/70767436/a383375e-6bcb-441a-ad50-4a9e9cb1d0f1)

Farmer's Delight: 1.3.9
Minecraft: 1.19.2

**Comment by Zifiv** [comment]
Hello @xlifi,

Thank you for reporting the issue, it seems to be a bug, I'll check with the Forge version, but it should be like all netherite items, fire/lava resistant.
