### ISSUE TITLE
Rice only drops a Straw when harvested with a Knife

### ISSUE THREAD

**Issue by Dekamir** [newhoryzon/farmers-delight-fabric#150]
Title self-explanatory.
It does not drop the Rice Panicle.
Does drop a Rice Panicle when harvested without it.

**Comment by Mat-a-tat** [comment]
Howdy! Did some digging, and it does seem rice patties were missing from the straw loot list. I added a pull request to the main, but! If you wan't to add it to your game proper, or want to see the code:

`"pools": [
  {
    "rolls": 1,
    "entries": [
      {
        "type": "minecraft:item",
        "name": "farmersdelight:straw"
      }
    ],
    "conditions": [
      {
        "condition": "minecraft:match_tool",
        "predicate": {
          "tag": "farmersdelight:straw_harvesters"
        }
      },
      {
        "condition": "block_state_property",
        "block": "farmersdelight:rice_crop",
        "properties": {
          "age": "3"
        }
      }
    ]
  }
]`

**Comment by Zifiv** [comment]
Hello @Dekamir (and @Mat-a-tat),

This is not a bug, to get rice panicle you shouldn't use knives and you should break the top block of rice crops (with your hand for example).


Knives is used to get straw on plants.
