### ISSUE TITLE
cant plant on rich soil farmland

### ISSUE THREAD

**Issue by m0thknight** [newhoryzon/farmers-delight-fabric#157]
I cant plant on rich soil farmland with some crops
![2023-06-11_12 36 06](https://github.com/newhoryzon/farmers-delight-fabric/assets/124231845/3aee297c-4d2e-4526-bd16-b1b94bd8113a)
here is a photo of me not being able to do that.

fabric version: 0.14.21
minecraft version: 1.19.2
farmer's delight fabric version: 1.0.1
here is a mod list:
	- adaptive-tooltips 1.0.1
	- advancementplaques 1.4.6
	- airhop 4.2.1
	- allay 4.1.0
	- alloy_forgery 2.0.20+1.19
	- angling 1.0.1
	- animal_feeding_trough 1.0.3+1.19.2
	- another_furniture 2.1.2-1.19.2
	- appleskin 2.4.1+mc1.19
	- architectury 6.5.85
	- axolotlitemfix 1.1.4
	- barteringstation 4.0.3
	- basicshields 1.4.0-1.19.2
	   \-- crowdin-translate 1.4+1.19
	- bcc 2.0.2-build.16+mc1.19.1
	- bclib 2.1.7
	- beekeeperhut 1.2.0
	- betteradvancements 0.3.0.148
	- betterdungeons 1.19.2-Fabric-3.2.1
	- bettermineshafts 1.19.2-Fabric-3.2.0
	- betteroceanmonuments 1.19.2-Fabric-2.1.0
	- bettershields 0.0.1-1.19.2
	- betterstats 2.8.1+1.19.2
	   \-- tcdcommons 2.8+1.19.2
	- betterstrongholds 1.19.2-Fabric-3.2.0
	- betterthanmending 1.3.0
	- betterthirdperson 1.9.0
	- bettertridents 4.0.2
	- betterwitchhuts 1.19.2-Fabric-2.1.0
	- biomemakeover 1.19.2-1.6.4
	- blastproof_netherite 2.0.0+mc1.19
	- blockrunner 4.2.2
	- blur 2.6.0
	- bonezone 1.0.3
	- bookshelf 16.3.20
	- botanypots 9.0.33
	- botanytrees 5.0.8
	- botarium 1.8.2
	   \-- team_reborn_energy 2.2.0
	- bountiful 3.0.0
	- bovinesandbuttercups 1.6.1+1.19.2-fabric
	   |-- cardinal-components-base 5.0.2
	   |-- cardinal-components-entity 5.0.2
	   \-- com_github_llamalad7_mixinextras 0.2.0-beta.8
	- brewinandchewin fabric-1.0.6+1.19.2
	- capybara 2.0.1
	- cardinal-components 5.0.2
	   |-- cardinal-components-base 5.0.2
	   |-- cardinal-components-block 5.0.2
	   |-- cardinal-components-chunk 5.0.2
	   |-- cardinal-components-entity 5.0.2
	   |-- cardinal-components-item 5.0.2
	   |-- cardinal-components-level 5.0.2
	   |-- cardinal-components-scoreboard 5.0.2
	   \-- cardinal-components-world 5.0.2
	- carryon 2.0.5.11
	- catalogue 1.7.0-1.19.2
	- cave_enhancements 1.19.2-2.1.12-fabric
	- charm 4.4.4
	   \-- com_moandjiezana_toml_toml4j 0.7.2
	- charm_fixer 1.0.0
	- charmofundying 6.2.0+1.19.2
	- chat_heads 0.10.14
	- chefsdelight 1.0.3-fabric-1.19.2
	   \-- structurized-reborn 1.19-01
	- cherishedworlds 6.0.5+1.19.4
	- chimes 1.1.4
	- chubbystuff 2.0.1-fabric
	- cinderscapes 3.0.5
	   |-- cinderscapes-client 3.0.5
	   |-- cinderscapes-common 3.0.5
	   |-- cinderscapes-worldgen 3.0.5
	   |-- terraform-biome-remapper-api-v1 4.1.1
	   \-- terraform-shapes-api-v1 4.1.1
	- cleardespawn 1.1.10
	- cloth-config 8.2.88
	   \-- cloth-basic-math 0.6.1
	- clumps 9.0.0+14
	- coalexplosion 1.6.2
	- collective 6.57
	- colorfulazaleas 2.3.1
	- colorize 1.4.0
	- companion 3.2.1
	- configured 2.0.0
	- continuity 2.0.2+1.19
	- coppergolem 2.0.0
	- corgilib 1.0.0.34
	   |-- com_electronwill_night-config_core 3.6.6
	   \-- com_electronwill_night-config_toml 3.6.6
	- crafttweaker 10.1.44
	   |-- org_javassist_javassist 3.29.0-GA
	   \-- org_reflections_reflections 0.10.2
	- creeperoverhaul 2.0.9
	- crittersandcompanions 1.19.2-2.0.1
	- crops_love_rain 1.3.0
	- cropxp 1.19.2-1.2.0
	- ctov 3.2.3
	- ctov_bountifulcompat_mr 1.0
	- ctov_chefsdelightaddon_mr 1.0
	- ctov_farmersdelightcompat_mr 1.2
	- ctov_morevillagerscompat_mr 1.1
	- culturaldelights 0.14.9+1.19.2
	   \-- terraform-wood-api-v1 4.2.0
	- cutehermitcrabs 2.0.3-1.19.2
	- darkpaintings 13.1.5
	- dawn 3.5.0
	- decorative_blocks 3.0.0
	- deeperdarker 1.1.6
	   |-- customportalapi 0.0.1-beta54-1.19
	   \-- paragon 3.0.2
	- deepslatecutting 1.5.0
	- delightful-froge 0.1.0+1.19
	- despawningeggshatch 4.1
	- dragonloot 1.1.2
	- driedbamboo ${version}
	- droplight 1.0.5
	- duckling 2.0.8
	- dummmmmmy 1.19.2-1.7.1
	- easyanvils 4.0.11
	- easymagic 4.3.3
	- easyshulkerboxes 4.4.1
	- ecologics 2.1.11
	- editenchanting 1.1.0
	- effective 1.4
	- effectivecrystals 1.1
	- elytraslot 6.1.1+1.19.2
	- enchantinginfuser 4.2.2
	- enchdesc 13.0.14
	- end_additions 3.0.5
	- enderscape 0.4.1-1.19.2
	   \-- mm 2.3
	- endrem 5.2.0
	- endsky 1.4
	- enhancedcelestials 2.1.0.5
	- entityculling 1.6.1-mc1.19.2
	- equipmentcompare 1.3.1
	- everycomp 1.19.2-2.4.9a
	- expandability 7.0.0
	- explorerscompass 1.19.2-2.2.0-fabric
	- explorify-fabric 1.19-1.3.0
	- extractinator 2.0.1
	- fabric-api 0.76.0+1.19.2
	   |-- fabric-api-base 0.4.15+8f4e8eb390
	   |-- fabric-api-lookup-api-v1 1.6.14+93d8cb8290
	   |-- fabric-biome-api-v1 9.1.1+16f1e31390
	   |-- fabric-block-api-v1 1.0.2+e415d50e90
	   |-- fabric-blockrenderlayer-v1 1.1.25+cafc6e8e90
	   |-- fabric-client-tags-api-v1 1.0.5+b35fea8390
	   |-- fabric-command-api-v1 1.2.16+f71b366f90
	   |-- fabric-command-api-v2 2.2.1+413cbbc790
	   |-- fabric-commands-v0 0.2.33+df3654b390
	   |-- fabric-containers-v0 0.1.41+df3654b390
	   |-- fabric-content-registries-v0 3.5.2+7c6cd14d90
	   |-- fabric-convention-tags-v1 1.3.0+4bc6e26290
	   |-- fabric-crash-report-info-v1 0.2.8+aeb40ebe90
	   |-- fabric-data-generation-api-v1 5.3.8+413cbbc790
	   |-- fabric-dimensions-v1 2.1.35+0d0f210290
	   |-- fabric-entity-events-v1 1.5.4+9244241690
	   |-- fabric-events-interaction-v0 0.4.34+562bff6e90
	   |-- fabric-events-lifecycle-v0 0.2.36+df3654b390
	   |-- fabric-game-rule-api-v1 1.0.24+b6b6abb490
	   |-- fabric-item-api-v1 1.6.6+b7d1888890
	   |-- fabric-item-groups-v0 0.3.39+9244241690
	   |-- fabric-key-binding-api-v1 1.0.25+5c4fce2890
	   |-- fabric-keybindings-v0 0.2.23+df3654b390
	   |-- fabric-lifecycle-events-v1 2.2.4+1b46dc7890
	   |-- fabric-loot-api-v2 1.1.13+83a8659290
	   |-- fabric-loot-tables-v1 1.1.16+9e7660c690
	   |-- fabric-message-api-v1 5.0.7+93d8cb8290
	   |-- fabric-mining-level-api-v1 2.1.24+33fbc73890
	   |-- fabric-models-v0 0.3.21+c6af733c90
	   |-- fabric-networking-api-v1 1.2.11+10eb22f490
	   |-- fabric-networking-v0 0.3.28+df3654b390
	   |-- fabric-object-builder-api-v1 4.2.2+d8ef690890
	   |-- fabric-particles-v1 1.0.14+4d0d570390
	   |-- fabric-recipe-api-v1 1.0.1+413cbbc790
	   |-- fabric-registry-sync-v0 0.9.32+9244241690
	   |-- fabric-renderer-api-v1 1.2.1+1adbf27790
	   |-- fabric-renderer-indigo 0.8.0+1adbf27790
	   |-- fabric-renderer-registries-v1 3.2.24+df3654b390
	   |-- fabric-rendering-data-attachment-v1 0.3.19+6e0787e690
	   |-- fabric-rendering-fluids-v1 3.0.11+4d0d570390
	   |-- fabric-rendering-v0 1.1.27+df3654b390
	   |-- fabric-rendering-v1 1.12.1+d8ef690890
	   |-- fabric-resource-conditions-api-v1 2.1.2+aae9039d90
	   |-- fabric-resource-loader-v0 0.8.4+edbdcddb90
	   |-- fabric-screen-api-v1 1.0.32+4d0d570390
	   |-- fabric-screen-handler-api-v1 1.3.7+1cc24b1b90
	   |-- fabric-sound-api-v1 1.0.2+c4f28df590
	   |-- fabric-textures-v0 1.0.24+aeb40ebe90
	   |-- fabric-transfer-api-v1 2.1.6+413cbbc790
	   \-- fabric-transitive-access-wideners-v1 1.3.3+08b73de490
	- fabric-language-kotlin 1.9.5+kotlin.1.8.22
	   |-- org_jetbrains_kotlin_kotlin-reflect 1.8.22
	   |-- org_jetbrains_kotlin_kotlin-stdlib 1.8.22
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.8.22
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.8.22
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.20.2
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.7.1
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.7.1
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.5.1
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.5.1
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.5.1
	- fabricloader 0.14.21
	- fabricshieldlib 1.7-1.19.2
	- farmer_allays 1.0
	- farmersdelight 1.19.2-1.3.9
	- farmersknives 2.4
	- farmersrespite 2.2.4
	   \-- porting_lib 2.1.656+1.19.2
	        |-- forge_tags 3.0
	        |-- porting_lib_base 2.1.656+1.19.2
	        |    \-- serialization_hooks 0.3.26
	        |-- porting_lib_entity 2.1.656+1.19.2
	        |-- porting_lib_lazy_registration 2.1.656+1.19.2
	        |-- porting_lib_model_generators 2.1.656+1.19.2
	        |-- porting_lib_models 2.1.656+1.19.2
	        |-- porting_lib_networking 2.1.656+1.19.2
	        |-- porting_lib_obj_loader 2.1.656+1.19.2
	        |    \-- porting_lib_model_loader 2.1.656+1.19.2
	        \-- porting_lib_transfer 2.1.656+1.19.2
	             \-- porting_lib_extensions 2.1.656+1.19.2
	                  |-- porting_lib_accessors 2.1.656+1.19.2
	                  |-- porting_lib_attributes 2.1.656+1.19.2
	                  |    \-- porting_lib_constants 2.1.656+1.19.2
	                  \-- porting_lib_common 2.1.656+1.19.2
	- faux-custom-entity-data 2.0.2
	- fennecfox 1.0.0
	- findme 3.1.0
	- flowerymooblooms 1.0.0
	- forgeconfigapiport 4.2.11
	- fpsreducer 1.19.2-2.1
	- frame 0.26.1+1.19-fabric
	   |-- frame-api-base 0.2.1+906ebc04a9
	   |-- frame-blocks-v0 0.1.3+233e7428a9
	   |-- frame-config-v0 0.3.1+0fa45150a9
	   |-- frame-content-registries-v0 0.4.0+2876b511a9
	   |-- frame-enchantments-v0 0.1.0+4093105da9
	   |-- frame-game-rules-v0 0.2.4+e7ce56a6a9
	   |-- frame-items-v0 0.1.3+906ebc04a9
	   |-- frame-loot-tables-v0 0.1.4+4f7341eca9
	   |-- frame-registries-v0 0.1.1+0e0ec74ea9
	   |-- frame-rendering-v0 0.1.5+906ebc04a9
	   |-- frame-tabbed-item-groups-v0 0.2.4+0aca9b56a9
	   |-- frame-toymaker-v0 0.6.1+b13741c3a9
	   \-- frame-woods-v0 0.2.1+6a33fbada9
	- friendsandfoes 1.8.2
	- froglegs 1.0.4
	- frostiful 0.5.4
	- frozenup 2.1.0-fabric
	- galosphere 1.19.2-1.3.0
	- geckolib3 3.1.40
	   \-- com_eliotlash_mclib_mclib 20
	- geode 1.1.8
	   \-- paragon 3.0.2
	- geodes 1.7+1.19
	- geophilic 1.19-2.0.0b
	- glare 1.0.1
	- goated 1.19.2-1.3.1
	- goblintraders 1.8.1
	- goodall 1.2.0
	- goodending 1.19.2-1.0.2-fabric
	- grindenchantments 3.1.1+1.19.2
	   \-- codec-config-api 1.0.2+1.19.3
	- handcrafted 2.0.6
	- harvest_scythes 2.5.4+mc1.19.2
	- harvestseason 1.19.2-1.2.1
	- harvestwithease 6.0.1.2-final
	- highlighter 1.1.4
	- hookshot 26.0
	- horseexpert 4.0.0
	- iceberg 1.0.46
	- illuminations 1.10.11
	- immersive_armors 1.5.5+1.19.2
	- immersive_weathering 1.19.2-1.2.9
	- impaled 1.1.4
	- improvedvanilla 1.19.2-1.6.3
	- indium 1.0.9+mc1.19.2
	- infinitetrading 4.0
	- ingredient-extension-api 3.0.6
	- inmis 2.7.1-1.19
	- inmisaddon 1.0.4
	- inventorysorter 1.8.10-1.19
	- iris 1.6.4
	   |-- io_github_douira_glsl-transformer 2.0.0-pre13
	   |-- org_anarres_jcpp 1.4.14
	   \-- org_antlr_antlr4-runtime 4.11.1
	- itemborders 1.1.6
	- jamlib 0.6.0+1.19
	- java 17
	- kambrik 4.0-1.19.2
	- kiwi 8.3.3
	- konkrete 1.6.1
	- labels 1.19.2-1.9
	- lambdabettergrass 1.3.0+1.19
	- lambdynlights 2.2.0+1.19.2
	   |-- pride 1.1.2+1.19
	   \-- spruceui 4.1.0+1.19.2
	- leavesbegone 4.0.1
	- legendarytooltips 1.3.3
	- letmedespawn fabric-1.0.2
	- libertyvillagers 1.0.14+fabric+1.19.2
	   \-- server_translations_api 1.4.18+1.19.2
	        \-- packet_tweaker 0.3.0+1.18.2
	- libraryferret 4.0.0
	- lithium 0.11.1
	- lootintegrations 1.19.3-3.1
	- lovely_snails 1.1.0+1.19
	- mantori 1.1.3-1.19.2
	- mavapi 1.0.1
	- mavm 1.2.0
	- mcpitanlibarch 1.6.4-1.19.2-fabric
	   \-- org_yaml_snakeyaml 2.0
	- mcwpaintings 1.0.4
	- meowing 1.0.1+1.19.2
	- midnightlib 1.0.0
	- mighty_mangoes 1.0.7
	- minecraft 1.19.2
	- mixin-conflict-helper 1.2.0
	- mixintrace 1.1.1+1.17
	- mob_captains_mr 1-v2.1.2
	- mob_catcher 1.2.15
	- mobscarecrow 2.2.1-1.19.1
	- modmenu 4.2.0-beta.2
	- moocow 1.19.2-1.0
	- moonlight 1.19.2-2.2.38
	- mooshroomtweaks 3.2
	- morebows 1.0.10+1.19.2
	- moremobvariants 1.0.1
	- morevillagers 4.0.2
	- mousetweaks 2.22
	- mousewheelie 1.11.1+mc1.19.2
	   |-- amecsapi 1.4.0+mc22w17a
	   |-- coat 1.0.0-beta.20+mc22w17a
	   |-- tweed4_annotated 1.3.1+mc22w17a
	   |-- tweed4_base 1.7.1+mc22w17a
	   |-- tweed4_data 1.2.1+mc22w17a
	   |-- tweed4_data_hjson 1.1.1+mc22w17a
	   |-- tweed4_tailor_coat 1.1.3+mc22w17a
	   |-- tweed4_tailor_lang_json_descriptions 1.1.0+mc22w17a
	   \-- tweed4_tailor_screen 1.1.4+mc22w17a
	- moyai 1.19.2-2.0.1
	- mru 0.1.5+1.19.2
	   \-- com_sksamuel_scrimage_scrimage-core 4.0.31
	- mvs 2.5.10-1.19.2
	- naturalist 3.0.3a
	- naturescompass 1.19.2-2.1.0-fabric
	- nbtcrafting 2.2.3+mc1.19
	- nears 1.2.3
	- netherdepthsupgrade fabric-3.0.0-1.19.2
	- nethersdelight 1.0.1
	   \-- disable_custom_worlds_advice 3.0
	- nicer-skies 1.2.0
	- nightconfigfixes 4.0.7
	- nightlights 1.1
	- nullscape 1.2.1
	- overweight_farming 1.19.2-2.0.2-fabric
	   |-- playerabilitylib 1.6.0
	   |-- reach-entity-attributes 2.3.0
	   \-- terraform-wood-api-v1 4.2.0
	- owo 0.9.3+1.19
	   \-- blue_endless_jankson 1.2.1
	- particlemoths 1.0.1+1.19
	   \-- cactusconfig 1.2.2+1.19
	- particlerain 2.0.0
	- paxi 1.19.2-Fabric-3.0.1
	- pettable 1.3.1
	- pickupnotifier 4.2.4
	- pickyourpoison 1.0.11
	   |-- cardinal-components-base 5.0.2
	   |-- cardinal-components-entity 5.0.2
	   \-- org_json_json 20211205
	- pineapple_delight 1.0.6
	- platypus 1.0.0
	- polymorph 0.46.1+1.19.2
	   \-- spectrelib 0.11.0+1.19
	- prism 1.0.3
	- probablychests 0.5.5-1.19.2
	- promenade 2.7.1
	- puzzleslib 4.4.0
	   |-- cardinal-components-base 5.0.2
	   |-- cardinal-components-block 5.0.2
	   |-- cardinal-components-chunk 5.0.2
	   |-- cardinal-components-entity 5.0.2
	   \-- cardinal-components-world 5.0.2
	- pyrotastic 1.19+2.0.3
	- quickshulker 1.3.9-1.19
	   |-- kyrptconfig 1.4.16-1.19
	   \-- shulkerutils 1.0.4-1.19
	- rare-ice 0.5.0
	- ratsmischief 1.4.0
	- realisticsleep 1.7.0
	- regenerations 1.0.2
	- replanter 1.3
	- replantingcrops 5.1
	- repurposed_structures 6.3.24+1.19.2
	- resourcefulconfig 1.0.20
	- resourcefullib 1.1.24
	- retraining 1.2.0
	- rottencreatures 1.0.1
	   \-- reach-entity-attributes 2.3.0
	- rottenleather 1.19.2-1.4
	- roughlyenoughitems 9.1.619
	   \-- error_notifier 1.0.9
	- satin 1.9.0
	- scorpions 1.3.1
	- shinyhorses 1.0.0
	- silkspawners 1.1.2
	- skeletalremains 1.3.2
	   \-- omega-config 1.3.0+1.19.2
	- skeletonhorsespawn 3.6
	- skinlayers 1.5.2-mc1.19.1
	- skylorlib 1.5.1
	- smarterfarmers 1.19.2-1.7.2
	- snowpig 2.0.0+build.27
	   \-- disable_custom_worlds_advice 3.0
	- snowrealmagic 5.1.1
	- snowundertrees 1.0.0+1.19.2
	- snowyspirit 1.19.2-2.1.10
	- sod 23.5.28
	- sodium 0.4.4+build.18
	   \-- org_joml_joml 1.10.4
	- spark 1.10.37
	   \-- fabric-permissions-api-v0 0.1-SNAPSHOT
	- spelunkery 1.19.2-0.2.2
	- spirit 2.2.6
	- sprout 1.4.4
	- stitchedsnow 1.0.5
	- striders-grace 1.0.0
	- structory 1.0.1
	- stylisheffects 4.3.4
	- supplementaries 1.19.2-2.3.17
	- swampier_swamps 1.19-1.2.1
	- takesapillage 1.0.4
	- taxfreelevels 1.3.3
	- terrablender 2.0.1.136
	- thermoo 1.4
	- thonkutil 2.15.4+1.19
	   |-- thonkutil-base 1.13.2+4a8c408a57
	   |-- thonkutil-capes-v1 1.4.2+3eb2749857
	   |-- thonkutil-coords-v1 1.1.2+8ff533c957
	   |-- thonkutil-customization-v1 1.1.2+8ff533c957
	   |-- thonkutil-legacy 1.1.2+5d4263f557
	   |-- thonkutil-modchecker-v1 1.1.3+bd4b387957
	   |-- thonkutil-potions-v0 1.5.2+8ff533c957
	   |-- thonkutil-titlescreen-v1 1.2.2+8ff533c957
	   \-- thonkutil-trades-v1 1.2.2+8ff533c957
	- toolstats 12.0.2
	- totemmod 0.3.6-1.19-pre1
	- tradingpost 4.2.0
	- travelerstitles 1.19.2-Fabric-3.1.0
	- treeharvester 8.1
	- trinkets 3.4.2
	- trulytreasures 1.19-2.0.2
	- tumbleweed 0.5.1
	- twigs 3.0.0
	- universalbonemeal 4.2.0
	- universalenchants 4.2.15
	   \-- extensibleenums 4.0.0
	- unsaddle 0.2.1
	   |-- unsaddle-compat-1-15 0.2.1
	   |-- unsaddle-compat-1-16 0.2.1
	   \-- unsaddle-core 0.2.1
	- vanillabetterbiomes 1.0.7-fabric-1.19.2
	- villagersrespawn 5
	- visuality 0.5.6
	- visualworkbench 4.2.4
	- vitalize 1.1.1
	- vulture 1.0.1
	- wandering_trapper 2.0.0
	- warriorrage 1.19.2-fabric-1.0.3
	- windchimes 1.2.1
	- winterly 0.8.3
	   \-- cardinal-components-world 5.0.2
	- wolfarmorcompat 1.0.2-1.19.2
	- wolveswitharmor 1.8.0-1.19
	   |-- maybe-data 1.3.2-1.19-rc2
	   \-- static-content 1.0.1-1.16.2
	        \-- staticdata 1.1.2
	- woof 4.0.1-1.19.2
	- worldnamegen 0.1.2+1.19
	- xaeroworldmap 1.30.3
	- ydms_redpanda 1.0.3
	- yet-another-config-lib 2.2.0-for-1.19.2
	- yungsapi 1.19.2-Fabric-3.8.9
	- yungsextras 1.19.2-Fabric-3.1.0
	- zombievillagersfromspawner 3.4

**Comment by Zifiv** [comment]
Hello @m0thknight,

Thanks for the report.

Like I've said in an older issue (#30), it caused by an incompatibility with another mods that change and override how farmland blocks is detected.
I've already added the block rich soil farmland to the tag that is used by some mods to know that it's a farmland block.

The fix will be present in next release.
