### ISSUE TITLE
SlotInvalidRangeException: Slot 8 not in valid range - [0,8)

### ISSUE THREAD

**Issue by m0thknight** [newhoryzon/farmers-delight-fabric#158]
SlotInvalidRangeException: Slot 8 not in valid range - [0,8)

https://crashy.net/f8c20513-dafb-4bca-9a0c-19ee4b2dcb24

**Comment by Zifiv** [comment]
Hi @m0thknight,

Thanks for reporting this issue, it will be fixed by the implementation of fabric transfert api : #104.
