### ISSUE TITLE
Version 1.3.10 for 1.19.2 causes the game to crash on start up when used with Brewin' and Chewin'

### ISSUE THREAD

**Issue by NolanHewitt** [newhoryzon/farmers-delight-fabric#166]
Breaks this mod: https://www.curseforge.com/minecraft/mc-mods/brewin-and-chewin-fabric

1.3.9 did not have this issue. Tested on fabric 1.19.2

**Comment by Zifiv** [comment]
Hello @NolanHewitt,

Can you please add the log file error, to see what is wrong, but I think that author of Brewin' and Chewin' need to make a new update due to changes in the 1.3.10, try asking to the author of this mod first.
