### ISSUE TITLE
using "c" tags namespace instead of "fabric"

### ISSUE THREAD

**Issue by JieningYu** [newhoryzon/farmers-delight-fabric#18]
most fabric mods use "c" tags namespace but not "fabric".
only tool types use "fabric" namespace.

**Comment by beaucoralk** [comment]
Issue #1 will be resolved by this one (I keep it because it is more encompassing).

**Comment by Zifiv** [comment]
Issue #23 will be resolved by this one (I keep it because it is more encompassing).

**Comment by JieningYu** [comment]
Use https://github.com/AlphaMode/ForgeTags would be great.
