### ISSUE TITLE
Crash when looking at canvas sign

### ISSUE THREAD

**Issue by Tempest-5ky** [newhoryzon/farmers-delight-fabric#182]
Hey!
Just updated the mod, amongst others, on my server. Trying to render a chunk with a canvas sign block in it causes the following crash:

https://mclo.gs/gUcdMfy

Mod version is 3.1.20, minecraft version is 1.19.2 Fabric

**Comment by Zifiv** [comment]
Hello @Tempest-5ky,

Thank you for reporting the issue.
The log you give show that it's an error caused by the mod "Enhanced Block Entities". You can report the issue in the tracker of the mod : https://github.com/FoundationGames/EnhancedBlockEntities/issues.
