### ISSUE TITLE
Crash while eating Melon Popsicle

### ISSUE THREAD

**Issue by Lmaestre** [newhoryzon/farmers-delight-fabric#185]
i crafted and ate a melon popsicle and the game closed. i am plaing whith a few mods adn may be a conflict with one of them. i sent you the list on an image for you to see. I am sending the crash report and used chat gpt to narrow down the possible conflict, i hope it's usefull!

Conflicting code sugested by chat gpt3:
 java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1935.method_8389()" because "$$0" is null
	at net.minecraft.class_1799.<init>(class_1799.java:169)
	at net.minecraft.class_1799.<init>(class_1799.java:152)
	at com.nhoryzon.mc.farmersdelight.item.ConsumableItem.method_7861(ConsumableItem.java:67)

[crash-2023-07-30_00.34.18-server.txt](https://github.com/newhoryzon/farmers-delight-fabric/files/12208467/crash-2023-07-30_00.34.18-server.txt)
![mods](https://github.com/newhoryzon/farmers-delight-fabric/assets/140931305/ffec14ba-0993-4acf-a94e-9211010bd566)

The mod list

**Comment by AgentStormy44** [comment]
Issue #176 seems to have already reported this bug and been fixed in the next update

**Comment by Zifiv** [comment]
Hello @Lmaestre,

Thanks you for reporting this issue, but like @AgentStormy44 said, it is already done and reported in another bug and will be integrated in the next release.
