### ISSUE TITLE
[request] Glow Berry Cookies

### ISSUE THREAD

**Issue by N0aW** [newhoryzon/farmers-delight-fabric#187]
Since in vanilla minecraft, glow berries are identical in stats and usage to sweet berries, it would make sense to have Glow Berry cookies in contrast to Sweet Berry Cookies.

**Comment by Zifiv** [comment]
Hello @N0aW,

For any request to add something or modify functionnality I recommend you to ask the original author of the mod (forge version) via github discussions on the github repository here : https://github.com/vectorwing/FarmersDelight/discussions
