### ISSUE TITLE
Planting rice causes game to crash + become unloadable

### ISSUE THREAD

**Issue by CAgr1m13** [newhoryzon/farmers-delight-fabric#188]
Hello, I am currently on 1.20.1 using Farmers Delight v1.4.1
Like the title states, whenever I plant rice in water my game crashes and unloads
Luckily I had a back up of the world before I placed any rice so I am still able to play.

**Comment by Zifiv** [comment]
Hello @CAgr1m13,

Thank you for reporting this issue, but I can't reproduce the error, do you play on server or solo world ?
If it is on server, be sure that the mod is up to date on the server.

Plus, if you have any logs for the crash, it will be helpful to understand what's wrong.

**Comment by CAgr1m13** [comment]
I play on a solo world but I do use many other mods, I'm assuming there's some sort of conflict with another mod but im not sure.
I'll leave my crash log.

[latest.log](https://github.com/newhoryzon/farmers-delight-fabric/files/12245257/latest.log)

Thank you @Zifiv

**Comment by Zifiv** [comment]
I recommend you to re-download the new version of Farmer's Delight (mod should be download only on CurseForge site), because the log show a line of code that is not present in my code... I'm confused and don't understand what happen.

**Comment by C4uTi0N** [comment]
I'm also experiencing this, both on server and singleplayer

**Comment by C4uTi0N** [comment]
Apparently the "Seamless" mod doesnt like the rice crop
https://modrinth.com/mod/seamless

[crash-2023-08-03_17.41.39-client.txt](https://github.com/newhoryzon/farmers-delight-fabric/files/12252596/crash-2023-08-03_17.41.39-client.txt)

**Comment by Zifiv** [comment]
You right, it's caused by Seamless that is not updated for the last version of Farmer's Delight, you can create a new ticket on the issue tracker of Seamless mod.

Thanks @C4uTi0N for your help.
