### ISSUE TITLE
Pitcher Pods cannot be planted on Rich Soil Farmland

### ISSUE THREAD

**Issue by AngelTechnic** [newhoryzon/farmers-delight-fabric#189]
On Farmer's Delight fabric version 1.4.1, attempting to plant Pitcher Pods on Rich Soil Farmland does not work at all.

**Comment by BarchamMal** [comment]
I fix this in this [Fix a bug where pitcher pods can...](https://github.com/newhoryzon/farmers-delight-fabric/commit/ccf3a78a975664de9af0edf28f50e0587cba3c74) commit.
