### ISSUE TITLE
Crash when eating certain items

### ISSUE THREAD

**Issue by Sollace** [newhoryzon/farmers-delight-fabric#194]
Whilst I was adding integration with my own mod, I happened to try eating a popsickle and noticed a _tiny_ little crash to desktop.

Just letting you know you should check `Item#hasRecipeRemainder()` before calling `Item#getRecipeRemainder` over [here](https://github.com/newhoryzon/farmers-delight-fabric/blob/1264a3a3d248cf2fc96e4c278f9b120e1a794591/src/main/java/com/nhoryzon/mc/farmersdelight/item/ConsumableItem.java#L67).

The way the ItemStack constructor appears to be set up in 1.20 and above it doesn't appear to handle handle null args any more. Instead it goes to the ItemConvertable one which assumes the first arg is not null.

What you should probably do is change the line to be more like this:

```

ItemStack container = stack.getItem().hasRecipeRemainder() ? stack.getItem().getRecipeRemainder().getDefaultStack() : ItemStack.EMPTY;

```

**Comment by Zifiv** [comment]
Hello @Sollace,

Thank you for report this issue and for your help, this is already fixed but not release, it will be released this saturday/sunday.
