### ISSUE TITLE
[1.20.1]Cooking Pot Recipes not working on server

### ISSUE THREAD

**Issue by Darlingohaio** [newhoryzon/farmers-delight-fabric#196]
Have been playing with friends on athernos server with this mod loaded and suddenly Cooking Pot recipes stopped working (after shutting down server for night we run it again next day and this problem came).

engine - mohist 1.20.1 (344 - unknown)
Farmer's Delight version is 1.2.2a

and I don'r know wha to do

**Comment by Zifiv** [comment]
Hello @Darlingohaio,

You seems to use the forge version, there is no 1.2.2 version for Farmer's Delight fabric version.
