### ISSUE TITLE
Add more farming aspects to Farmer's Delight.

### ISSUE THREAD

**Issue by DaCooladeMan** [newhoryzon/farmers-delight-fabric#199]
This post is more of a pull request than an issue, but I couldn't figure out how to post a pull request, so I'm posting it here. Farmer's Delight is a really good food mod, if not the best food mod ever created. But it doesn't really have enough farming aspects to it. More cooking. I want it to 75% farming, 25% cooking, because it's called "Farmer's Delight" not "Chef's Delight". I want there to be a watering can, which you can use to water crops, **which** in turn, causes crops to grow 10% or 15% faster. There also needs to be Animal Waste and stuff which you can create fertilizer with to boost crop growing speed by 25%. There can also be a rake, which allows you to create farmland in a 3 by 3 square, more efficient than a hoe. There also needs to be other fruits, like bananas. I am unsure if a Farmer's Delight addon adds bananas to the game, but if not, there definitely needs to be a banana. You can create Banana Milkshakes out of it, which gives you a 1:00 speed boost when drank. Now, obviously bananas grow on trees, which there needs to be a banana tree sapling to farm bananas. There you have it. All of my suggestions for Farmer's Delight. I think they're good suggestions, considering that there are not a lot of farming tools in Farmer's Delight. I extremely enjoy this mod, and hope that it gets improved as the days go by.

**Comment by Zifiv** [comment]
Hello @DaCooladeMan,

This repository is only for Farmer's Delight fabric port.
I'm just porting Farmer's Delight, isn't in my goal to add feature that is not present on forge version.

So if you have any idea or suggestion to add feature or changes existing in Farmer's Delight, I recommend you to ask it in the forge version.

Issue tracker of forge version : https://github.com/vectorwing/FarmersDelight/issues
Discord of forge version : https://discord.gg/eFsz5SK

**Comment by DaCooladeMan** [comment]
> Hello @DaCooladeMan,
> 
> This repository is only for Farmer's Delight fabric port. I'm just porting Farmer's Delight, isn't in my goal to add feature that is not present on forge version.
> 
> So if you have any idea or suggestion to add feature or changes existing in Farmer's Delight, I recommend you to ask it in the forge version.
> 
> Issue tracker of forge version : https://github.com/vectorwing/FarmersDelight/issues Discord of forge version : https://discord.gg/eFsz5SK

Sorry, I thought that you can post your suggestions on both GitHub pages. I'll post my suggestions on the forge FD GitHub instead. Thanks for the help.
