### ISSUE TITLE
[1.20.1]Cooking Pot Recipes not working on server

### ISSUE THREAD

**Issue by Darlingohaio** [newhoryzon/farmers-delight-fabric#200]
Have been playing with friends on athernos server with this mod loaded and suddenly Cooking Pot recipes stopped working (after shutting down server for night we run it again next day and this problem came).

engine - mohist 1.20.1 (344 - unknown)
Farmer's Delight version is 1.2.2a

even when i install 100% the same mode for server and client it's still odesn't work

and I don't know what to do
![image](https://github.com/newhoryzon/farmers-delight-fabric/assets/66775231/de5281cc-8231-4936-abad-fc95a9b27237)

--------------------------------------------------------------------------------------------------------------------------------------------

![image](https://github.com/newhoryzon/farmers-delight-fabric/assets/66775231/4ce99b54-ab29-4740-ad94-eb358ee2da84)

![image](https://github.com/newhoryzon/farmers-delight-fabric/assets/66775231/8cbab569-382c-4227-bf82-2ed45a659715)

**Comment by Zifiv** [comment]
Hello @Darlingohaio,

You are using the forge version of Farmer's Delight, so I recommend you asking help in the forge issue tracker : https://github.com/vectorwing/FarmersDelight/issues.
