### ISSUE TITLE
Incompatibility with create steam n rails 1.5.0 fabric

### ISSUE THREAD

**Issue by BrickidyBlockidy** [newhoryzon/farmers-delight-fabric#203]
heya! so recently create steam n rails updated their mod to add new bogies, but it crashes when selecting the new bogies (pressing alt with train casing) if used with farmers delight fabric. i reported to them the problem and they said its a farmers delight incompatibility and i should go ask you guys. so here i am! any chance anything could be done to make them compatible?
[crash-2023-09-01_18.58.19-client.txt](https://github.com/newhoryzon/farmers-delight-fabric/files/12508465/crash-2023-09-01_18.58.19-client.txt)

**Comment by Zifiv** [comment]
Hello @BrickidyBlockidy,

Seems to have the same issue than #205, I keep the last one because it is more complete.
