### ISSUE TITLE
Items is not showing on Skillet

### ISSUE THREAD

**Issue by Ross2750** [newhoryzon/farmers-delight-fabric#204]
Version: 1.3.10.1 - 1.19-1.19.2
Items is not showing on Skillet when cooking

Screenshots:

Cooking on Stove
![2023-09-05_07 49 08](https://github.com/newhoryzon/farmers-delight-fabric/assets/122451270/ab469087-8100-44cd-91b7-aba362e23f40)

Portable Cooking
![2023-09-05_07 53 50](https://github.com/newhoryzon/farmers-delight-fabric/assets/122451270/c6161bb6-943f-420f-b20b-b8d3cc3fa9b8)

**Comment by DaCooladeMan** [comment]
It's a bug. Don't know when it'll get fixed. I've been patient all this time, and I ask for you to do the same. The team behind Farmer's Delight's Fabric port will fix this bug. It'll just take a long time because it's currently not their highest priority.

**Comment by Zifiv** [comment]
Hello @Ross2750,

Thank you for reporting this issue, it is kwown and an issue is already created, you can see the advancement on #41.
