### ISSUE TITLE
LOG Spam

### ISSUE THREAD

**Issue by ardissaps** [newhoryzon/farmers-delight-fabric#21]
so much, cant post it coz it is so much, unknown recipe category thing

**Comment by beaucoralk** [comment]
If it's about all the `Unknown recipe category: farmersdelight:...` lines added only at the start of the game (or the server), it will be fixed to the next release.
I add your issue to the milestone of the next release, thanks for the report 👍.

**Comment by ardissaps** [comment]
Is that problem relate to REI?

**Comment by beaucoralk** [comment]
It's not a problem with REI. There is some custom recipe type in Farmer's Delight, one for cooking in cookin pot, one for cutting in cutting board and the category of these recipes is not known by Minecraft. I should add new one and register it to the Minecraft.

**Comment by SpigotDE** [comment]
I have this too for 1.18.2 , could you fix this for this awesome version too pls

**Comment by ardissaps** [comment]
yeah up this, need fix for 1.18.2 too hehehe
