### ISSUE TITLE
How can I user items from other mod to heat the fruing pan.

### ISSUE THREAD

**Issue by Chanshes** [newhoryzon/farmers-delight-fabric#215]
How can I user items from other mod to heat the fruing pan.
like "pfm: white_stove" in "Paradin's Furniture"

**Comment by BarchamMal** [comment]
You would need to install or create a datapack that adds "pfm:white_stove" to the ```data/farmersdelight/tags/blocks/tray_heat_sources.json``` block tag.

**Comment by BarchamMal** [comment]
Also, you should reach out to @UnlikePaladin, the owner of [paladins-furniture](https://github.com/UnlikePaladin/paladins-furniture) and ask for compatibility with farmers-delight-fabric, as that is compatibility that can not be added on our side.

**Comment by UnlikePaladin** [comment]
This was actually just added in the 1.2 release of my mod because it was a requested feature
