### ISSUE TITLE
Cutting recipes for Cherry are missing

### ISSUE THREAD

**Issue by gniftygnome** [newhoryzon/farmers-delight-fabric#219]
There are no cutting board recipes for Cherry Log and Cherry Wood, so bark cannot be obtained from them.

**Comment by BarchamMal** [comment]
I fix this in this [Add recipe for stripping cherry log and wood.](https://github.com/newhoryzon/farmers-delight-fabric/commit/1c1d13e909661e8993047829c820a35daa7bea64) commit.
