### ISSUE TITLE
Problems with create: steam n rails [Fabric 1.19.2]

### ISSUE THREAD

**Issue by JedaiGames** [newhoryzon/farmers-delight-fabric#222]
Game is crashing when i trying to change bogey style in Create mod with ALT key.
Firstly I reported this issue to Create Steam n Rails itself, but they redirected me back to you:
https://github.com/Layers-of-Railways/Railway/issues/319

I'm using **Minecraft 1.19.2** with **Fabric 0.14.24**
Only mods i used are:

- Create Fabric 0.5.1c
- Create: Steam n Rails 1.5.1
- Farmers Delight 1.3.10.1
- JEI 11.6.0
- Fabric API 0.76.1
- Just Enough Farmers Recipes 1.0.1

Here's crash log after this happend.
https://mclo.gs/Mzh4m29

**Comment by liamwerk7676** [comment]
yeah it randomly crashes on the discord of steam and reals there is a port that woks with steam n rails

**Comment by Zifiv** [comment]
Hello @JedaiGames,

This bug has been fixed in last version of Farmer's Delight for 1.19.2 :

- Curseforge: https://www.curseforge.com/minecraft/mc-mods/farmers-delight-fabric/files/4939667
- Modrinth : https://modrinth.com/mod/farmers-delight-fabric/version/1.3.10.2

**Comment by liamwerk7676** [comment]
> Hello @JedaiGames,
> 
> This bug has been fixed in last version of Farmer's Delight for 1.19.2 :
> 
> * Curseforge: https://www.curseforge.com/minecraft/mc-mods/farmers-delight-fabric/files/4939667
> * Modrinth : https://modrinth.com/mod/farmers-delight-fabric/version/1.3.10.2

also for 1.20.1 ?
