### ISSUE TITLE
Backstab enchantment not exclusive to Knives

### ISSUE THREAD

**Issue by maeveuay** [newhoryzon/farmers-delight-fabric#26]
The Backstabbing enchantment is supposed to be exclusive to the Knife, however, it also can apply to swords.

In both my multiplayer and Singleplayer tests with my modpack, I am able to use an Enchanting Table or Book to add the Backstabbing enchantment to any sword.

![image](https://user-images.githubusercontent.com/108652136/177503228-8ab0dd13-98cd-440e-88d9-23e2bbb6737a.png)

	Fabric Mods: 
		additionaladditions: Additional Additions 5.0.1
			libgui: LibGui 6.0.0-beta.5+1.19-pre1
				jankson: Jankson 4.1.1+j1.2.1
					blue_endless_jankson: jankson 1.2.1
				libninepatch: LibNinePatch 1.1.0
		additionalstructures: Additional Structures 4.0.0
		adorn: Adorn 3.5.4+1.19
		alternate-current: Alternate Current 1.4.0
		antighost: AntiGhost 1.19-fabric0.55.3-1.1.5
			crowdin-translate: CrowdinTranslate 1.4+1.19
		appleskin: AppleSkin 2.4.0+mc1.19
		architectury: Architectury 5.7.28
		attributefix: AttributeFix 15.0.1
		balm-fabric: Balm 4.3.0+0
		beaconoverhaul: Beacon Overhaul 1.7.0+1.19
			fabric-api-base: Fabric API Base 0.4.9+e62f51a3a9
			fabric-networking-api-v1: Fabric Networking API (v1) 1.0.27+7fe97409a9
			reach-entity-attributes: Reach Entity Attributes 2.3.0
		beenfo: Beenfo 1.19-fabric0.53.3-1.3.3
			gbfabrictools: GBfabrictools 1.3.4+1.19
		betteradvancements: Better Advancements 0.2.1.134
		betterbeds: Better Beds 1.2.0
		betterpingdisplay: Better Ping Display 1.1.1
		birdsnests: Bird's Nests 1.0.0+1.19
		boatcontainer: BoatContainer 1.2.0
		bookshelf: Bookshelf 14.0.3
		chalk: Chalk 2.1.0+1.19
		charmonium: Charmonium 4.1.0
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		cleancut: CleanCut 1.19-5.0-fabric
		clickthrough: ClickThrough 1.19-fabric0.53.3-0.4
		clienttweaks: Client Tweaks 8.0.0
		cloth-config: Cloth Config v6 7.0.72
			cloth-basic-math: cloth-basic-math 0.6.1
		clumps: Clumps 9.0.0+3
		collective-fabric: Collective (Fabric) 4.27
			fiber: fiber 0.23.0-2
		comforts: Comforts 6.0.0-beta.2+1.19
			cardinal-components-base: Cardinal Components API (base) 5.0.0-beta.1
			cardinal-components-entity: Cardinal Components API (entities) 5.0.0-beta.1
			spectrelib: SpectreLib 0.4.0+1.19
		couplings: Couplings 1.9.0+1.19
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
		crawl: Crawl 0.11.0
			mm: Manningham Mills 2.3
		dark-loading-screen: Dark Loading Screen 1.6.12
		darkness: True Darkness 2.0.94
		darkpaintings: DarkPaintings 11.0.2
		dummmmmmy: MmmMmmMmmMmm 1.19-1.5.3
		eatinganimationid: Eating Animation 1.8.1
		effective: Effective 1.2.2
		enhancedblockentities: Enhanced Block Entities 0.7.1+1.19
			advanced_runtime_resource_pack: Runtime Resource Pack 0.6.2
			spruceui: SpruceUI 4.0.0+1.19
		enhancedcelestials: Enhanced Celestials 2.0.0.0
		entityculling: EntityCulling-Fabric 1.5.2-mc1.19
			com_logisticscraft_occlusionculling: occlusionculling 0.0.6-SNAPSHOT
		fabric: Fabric API 0.57.0+1.19
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.7+9ff28f40a9
			fabric-biome-api-v1: Fabric Biome API (v1) 9.0.14+b2a4a624a9
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.18+9ff28f40a9
			fabric-command-api-v1: Fabric Command API (v1) 1.2.6+f71b366fa9
			fabric-command-api-v2: Fabric Command API (v2) 2.1.2+0d55f585a9
			fabric-commands-v0: Fabric Commands (v0) 0.2.23+df3654b3a9
			fabric-containers-v0: Fabric Containers (v0) 0.1.27+df3654b3a9
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.2.0+07df213ea9
			fabric-convention-tags-v1: Fabric Convention Tags 1.0.8+37622d24a9
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.3+bd0a0d4aa9
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.1.1+a680b9b4a9
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.28+a6d2f785a9
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.16+9ff28f40a9
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.26+9ff28f40a9
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.25+df3654b3a9
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.19+18990361a9
			fabric-item-api-v1: Fabric Item API (v1) 1.5.4+767db26ea9
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.25+9ff28f40a9
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.18+9ff28f40a9
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.16+df3654b3a9
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.1.0+33fbc738a9
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.0+03a4e568a9
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.3+9e7660c6a9
			fabric-message-api-v1: Fabric Message API (v1) 1.0.1+513f4a59a9
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.10+33fbc738a9
			fabric-models-v0: Fabric Models (v0) 0.3.15+9ff28f40a9
			fabric-networking-v0: Fabric Networking (v0) 0.3.14+df3654b3a9
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.0.7+9ff28f40a9
			fabric-particles-v1: Fabric Particles (v1) 1.0.8+dc39553aa9
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.17+23c4cfefa9
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.0.8+9ff28f40a9
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.9+1f92344ea9
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.18+df3654b3a9
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.12+9ff28f40a9
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.5+9ff28f40a9
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.20+df3654b3a9
			fabric-rendering-v1: Fabric Rendering (v1) 1.10.14+9ff28f40a9
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.9+e62f51a3a9
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.5.5+a6d2f785a9
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.24+f05effafa9
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.6+9ff28f40a9
			fabric-textures-v0: Fabric Textures (v0) 1.0.18+9ff28f40a9
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.0.9+e62f51a3a9
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.1.1+9e7660c6a9
		fabric-language-kotlin: Fabric Language Kotlin 1.8.1+kotlin.1.7.0
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.7.0
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.7.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.7.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.7.0
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.18.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.3
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.3
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.3
		fabricloader: Fabric Loader 0.14.8
		farmersdelight: Farmer's Delight 1.19-0.3.0
		ferritecore: FerriteCore 4.2.1
		fwaystones: Fabric Waystones 3.0.1+mc1.19
		geckolib3: Geckolib 3.1.5
			com_eliotlash_mclib_mclib: mclib 18
			com_eliotlash_molang_molang: molang 18
		glassdoor: Glass Doors 3.0.0-rc.1+1.19
		handoveryouritems-fabric: Hand Over Your Items (Fabric) 1.5
		healthindicators: PlayerHealthIndicators 1.0.1
		herdspanic: Herds Panic 1.0.6
		hotbarcycle: Hotbar Cycle 1.1.0
		ia: Immersive Amethyst 1.0.5
		illuminations: Illuminations 1.10.8
		immersive_weathering: Immersive Weathering 1.0.1-1.19_SNAPSHOT
		indium: Indium 1.0.6+mc1.19
		inventoryprofilesnext: Inventory Profiles Next 1.5.3
		itemmodelfix: Item Model Fix 1.0.3+1.19
		java: OpenJDK 64-Bit Server VM 17
		lambdabettergrass: LambdaBetterGrass 1.3.0+1.19
		lambdynlights: LambDynamicLights 2.1.2+1.19
			pride: Pride Lib 1.1.2+1.19
		lazydfu: LazyDFU 0.1.3
		lithium: Lithium 0.8.0
		lovely_snails: Lovely Snails 1.1.0+1.19
		make_bubbles_pop: Make Bubbles Pop Mod 0.0.2-1.19
		megaparrot: Megaparrot 1.0.5
		midnightlib: MidnightLib 0.5.2
		minecraft: Minecraft 1.19
		moborigins: Mob Origins 1.9.0
		mobs_attempt_parkour: Mobs Attempt Parkour 0.3-1.19-pre1
			maelstrom_library: Maelstrom Library 1.3-1.19-pre1
		modmenu: Mod Menu 4.0.0
		moreculling: More Culling 1.19-0.4.0
			conditional-mixin: conditional mixin 0.3.0
		naturescompass: Nature's Compass 1.19-2.0.4-fabric
		no-telemetry: No Telemetry 1.4.0
		odysseyhud: OdysseyHUD 4.6
		origins: Origins 1.6.2
			apoli: Apoli 2.5.1
				additionalentityattributes: Additionalentityattributes 1.0.0+1.19
				calio: Calio 1.7.0
				playerabilitylib: Pal 1.6.0
		origins-classes: Origins: Classes 1.4.0
		patchouli: Patchouli 1.19-73-FABRIC
		pehkui: Pehkui 3.3.3+1.14.4-1.19.1
			kanos_config: Kanos Config 0.3.1+1.14.4-1.19
		pigeons: Pleasant Pigeons 1.4.0
		presencefootsteps: Presence Footsteps 1.6.1
			kirin: Kirin UI 1.11.0
		probablychests: Probably Chests 0.4.4
		publicguiannouncement: Public Gui Announcement 4.0.0.0
		raised: Raised 1.1.2
		realisticsleep: Realistic Sleep 1.5
		recipecache: recipecache 0.2.0-1.19
		reeses-sodium-options: Reese's Sodium Options 1.4.3+mc1.19-build.43
		rocks: This Rocks! 1.6.1
		roughlyenoughitems: Roughly Enough Items 9.1.500
		scout: Scout 1.0.1
		simply_houses: Simply Houses 1.1.1-1.19
		skylorlib: SkyLib 1.5.1
		snowyleavesplus: SnowyLeavesPlus 0.1.2
		sodium: Sodium 0.4.2+build.16
			org_joml_joml: joml 1.10.4
		spark: spark 1.9.13
			fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		starlight: Starlight 1.1.1+fabric.ae22326
		stb: Sneak Through Berries 5.0.0
		stoneholm: Stoneholm 1.4.4
		talkbubbles: Talk Bubbles 1.0.2
		thonkutil: ThonkUtil 2.15.3+1.19
			thonkutil-base: ThonkUtil Base 1.13.1+575521ba57
			thonkutil-capes-v1: ThonkUtil Capes (v1) 1.4.1+7ce8ef6257
			thonkutil-coords-v1: ThonkUtil Coords (v1) 1.1.1+8ff533c957
			thonkutil-customization-v1: ThonkUtil Customization (v1) 1.1.1+8ff533c957
			thonkutil-legacy: ThonkUtil Legacy 1.1.1+5d4263f557
			thonkutil-modchecker-v1: ThonkUtil ModChecker (v1) 1.1.1+8ff533c957
			thonkutil-potions-v0: ThonkUtil Potions (v0) 1.5.1+8ff533c957
			thonkutil-titlescreen-v1: ThonkUtil TitleScreen (v1) 1.2.1+8ff533c957
			thonkutil-trades-v1: ThonkUtil Trades (v1) 1.2.1+8ff533c957
		tipsmod: Tips 6.0.1
		trinkets: Trinkets 3.4.0
		vanityslots: Vanity Slots 1.2.0
		villager-hats: Villager Hats 1.4.1
		visuality: Visuality 0.5.0
		visualoverhaul: VisualOverhaul 4.1.1
		windchimes: Windchimes 1.2.1
		yigd: You're in Grave Danger 1.4.1

**Comment by Zifiv** [comment]
Hello @maeveuay, thanks you for submited this issue.

I confirm that in the "Enchanting table" you can apply Backstabbing to sword, I'll fix it.
But I can't reproduce applying Backstabbing enchanted book to a sword by using anvil, maybe you tried in creative mod (it's a normal behavior, in creative mode all book can be applied to all item with anvil).

**Comment by maeveuay** [comment]
> Hello @maeveuay, thanks you for submited this issue.
> 
> I confirm that in the "Enchanting table" you can apply Backstabbing to sword, I'll fix it. But I can't reproduce applying Backstabbing enchanted book to a sword by using anvil, maybe you tried in creative mod (it's a normal behavior, in creative mode all book can be applied to all item with anvil).

You are 100% correct, it can't be applied via Anvil, I was testing everything in creative.

**Comment by maeveuay** [comment]
(i am very new to github, so sorry XD)

**Comment by Zifiv** [comment]
No problem 😃.
I'm keeping the issue open until the version containing the fix is released.
