### ISSUE TITLE
[Foodtype Suggestion] Curry

### ISSUE THREAD

**Issue by dhi-holo** [newhoryzon/farmers-delight-fabric#28]
Farmer's Delight is a very cool mod, and I am excited to play with it more, but I noticed that Rice only has a few uses, and with the Tatami blocks also added by the mod, I thought some types of curry could be interesting to see.

Utilising rice, chicken cuts, milk, onions or tomato, and perhaps other ingredients, a bowl of curry could be created. Perhaps some alternate types of curries, with different sauce ingredients and meats could also exist, similar to stews/soups already present in the mod. The other ingredients could include stuff like cocoa beans, mutton chops, fish slices, bacon, or eggs.

**Comment by Zifiv** [comment]
Hello @dhi-holo, it seems to be a good suggestion :), thank for report it, but I'll not add things that is not in the initial mod (forge version). My goal is only to "port" the original mod for Fabric loader.
So you can repost your suggestion in the [github](https://github.com/vectorwing/FarmersDelight/issues) or [Discord](https://discord.gg/eFsz5SK) of original Farmer's Delight mod (forge version).
