### ISSUE TITLE
World Crash/World Softlock between Farmer's Delight and Dynamic Crosshair

### ISSUE THREAD

**Issue by AlexTheSuprWolf** [newhoryzon/farmers-delight-fabric#29]
with both mods installed, looking at any of the pantry blocks with an empty bucket in your hand will crash the game instantly.
This will softlock the world if it saves with you looking at the pantry block.

[crash-2022-07-09_21.40.47-client.txt](https://github.com/newhoryzon/farmers-delight-fabric/files/9078275/crash-2022-07-09_21.40.47-client.txt)

**Comment by Zifiv** [comment]
Thanks for the report, it seems that Dynamic Crosshair try to check the watterlog status of pantry block, but pantry block hasn't this property (because it's a full block).

You do not need to report it to Dynamic Crosshair.
