### ISSUE TITLE
Can't Plant Seed ond Rich Soil Farmland

### ISSUE THREAD

**Issue by ardissaps** [newhoryzon/farmers-delight-fabric#30]
![image](https://user-images.githubusercontent.com/82106625/178408209-a84911dd-addb-46dc-8d03-514e7577e7ec.png)

**Comment by Zifiv** [comment]
Hello @ardissaps, thanks to report the issue, but I can't reproduce it on latest version of 1.19 (_0.3.0_) and 1.18 (_0.2.1_) Minecraft version of the mod.

Can you tell me what is the version of Farmer's Delight you installed ?

**Comment by ardissaps** [comment]
Version I am using :
![image](https://user-images.githubusercontent.com/82106625/178643490-37254496-fa61-47a2-83fe-b72bb5d997bf.png)

**Comment by Zifiv** [comment]
I've tested it in fresh install with only Farmer's Delight, and it worked well.

Can you give me the complete list of mod that you are using and test only with Famer's Delight installed.

**Comment by ardissaps** [comment]
My mod list is very huge, I'll try to install FD alone on separate intance when I have chance.
![1](https://user-images.githubusercontent.com/82106625/178654584-63c4d704-a189-40b6-a447-a549caae2e13.jpg)

**Comment by Zifiv** [comment]
My guess, is there is a mod that override the method `canPlantOnTop` of **_CropBlock_** class with a mixin.

Do you know if there is a mod (in your list) that had new farmland blocks style ?

**Comment by ardissaps** [comment]
> My guess, is there is a mod that override the method `canPlantOnTop` of **_CropBlock_** class with a mixin.
> 
> Do you know if there is a mod (in your list) that had new farmland blocks style ?

Yes it is, [BYG ](https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go-fabric) have lush farmland.
![image](https://user-images.githubusercontent.com/82106625/178658338-352e1ec7-331f-4936-a1f8-f03ada2d463e.png)

**Comment by ardissaps** [comment]
Look like they have their own tag that only have their farmland and vanilla one :
![image](https://user-images.githubusercontent.com/82106625/178658632-e96b43cf-e611-42c4-bcb5-3cc7c5b018a0.png)

**Comment by Zifiv** [comment]
It seems that isn't a bad interaction with BYG, so it should be an another mod, but I've no idea which one.

**Comment by ardissaps** [comment]
> It seems that isn't a bad interaction with BYG, so it should be an another mod, but I've no idea which one.
> 
> In fact I could do the same as BYG fabric version do to integrate a new farmland, but in my opinion, it is not a good way.

I found it, the problem is caused by [MoreTags](https://modrinth.com/mod/moretags), the problem look like from their end. I already removed it and it works now. While for custom tag now I use KubeJS instead.
