### ISSUE TITLE
Can't place knife into board

### ISSUE THREAD

**Issue by SapphireFox420** [newhoryzon/farmers-delight-fabric#31]
Hey, 
Don't know if this is how it's supposed to be or if I'm doing something wrong but any tool I try shiftv - right clicking on the cutting board stay in it for a split second then it lays down on the cutting board. Would be cool if it'd stay upright. Not sure if this a a mod issue or game issue.

**Comment by Zifiv** [comment]
Hey @SapphireFox420, thanks you for submited this issue.

It is effectively a bug, by Shift+Right-Click on the cutting board with some items, it should stay like if you "planted it" on the cutting board.
This issue will be fix in the next release.
