### ISSUE TITLE
Mushroom colony unobtainable with shears

### ISSUE THREAD

**Issue by xtriel** [newhoryzon/farmers-delight-fabric#32]
unclear if i'm just doing something wrong or not, but left clicking a fully grown mushroom colony with shears doesn't seem to drop the mushroom colonies themselves anymore

**Comment by Zifiv** [comment]
Hello @xtriel, no you are right, there is a bug. The issue has been already reported (#23) and it will be fix in the next release by the issue about `c:` common tag usage (#18).
