### ISSUE TITLE
[Request] Other Mods Eggs Compatibility Ingredients

### ISSUE THREAD

**Issue by ardissaps** [newhoryzon/farmers-delight-fabric#34]
Would you please support one of these :

1. Accept **Eggs** from other mods like [Better Animal Plus](https://www.curseforge.com/minecraft/mc-mods/betteranimalsplus) for Farmer Delight Fried Egg?
![image](https://user-images.githubusercontent.com/82106625/179514756-f80eee0f-7da3-46ef-b568-8871d910c7c6.png)

**OR**

2. Accept the **Fried Eggs** from other mods for **Egg Sandwich** and **Noodle Soup**.
![image](https://user-images.githubusercontent.com/82106625/179515026-0f16abe4-0dd9-475e-9106-f83f8a207780.png)

**MC 1.18.2**

**Comment by JieningYu** [comment]
Tag issue

**Comment by ardissaps** [comment]
> Tag issue

How to fix it?

**Comment by JieningYu** [comment]
https://github.com/newhoryzon/farmers-delight-fabric/issues/18

**Comment by Zifiv** [comment]
I confirm that it is fixed by the issue about using the fabric common tag `c:`.
