### ISSUE TITLE
Seeds have wrong name

### ISSUE THREAD

**Issue by SandWoodJones** [newhoryzon/farmers-delight-fabric#35]
Both cabbage seeds and tomato seeds don't have seed in their names:
![image](https://user-images.githubusercontent.com/35671374/179618834-604e73d3-90d4-4ca4-a536-7bae799671e7.png)
![image](https://user-images.githubusercontent.com/35671374/179618894-1415b73e-8be5-4c81-9113-e8ee810c83bf.png)

**Comment by Zifiv** [comment]
Hello @SandWoodJones, thanks for the report, it will be fix by issue #13 that updates all translations files.

**Comment by erisdev** [comment]
This isn't actually fixed by the translation file update. The problem is that `BlockItem`s don't have their own translation string and just reuse the block's name. Seeds should be `AliasedBlockItem` instead.
