### ISSUE TITLE
No tool for deconstructing leather armor.  Should be shears.

### ISSUE THREAD

**Issue by shaffera777** [newhoryzon/farmers-delight-fabric#42]
The required tool for deconstructing leather armor into leather is blank, making it impossible to deconstruct leather armor.

**Comment by JieningYu** [comment]
https://github.com/newhoryzon/farmers-delight-fabric/issues/18

**Comment by Zifiv** [comment]
Hello @shaffera777, this issues has been already reported and the bug will be fix by the issue #18 like @JieningYu tell you.
