### ISSUE TITLE
issue with cooking pot not working, but does not have error codes or anything

### ISSUE THREAD

**Issue by azushade** [newhoryzon/farmers-delight-fabric#43]
a 1.19 private server between about five people has little to no issue (aside from an unrelated issue with leads duplicating that we've disabled some mods to try and fix), and the issue with the cooking pot recipes not being available, and the cooking pot itself not working. i have the expanded delight mod on top of farmers delight so i am thinking maybe that's causing issues? the full mod list is too big to list as most of them are miniscule QOL changes that have no impact on other mods, but i do have BYG and Origins if that means anything. i'm just confused as to why the recipes aren't showing up, and why the cooking pot isn't working, but everything else from the mod seems to be working fine?

**Comment by Zifiv** [comment]
Hello @azushade, did you try to test with only Farmer's Delight installed in your server ?
In general purpose, I can't help if issuer do not give some informations about the mod list at least, I'm not magician and I do not have the power of divination.

In my test with 0.3.0 of Farmer's Delight on 1.19 Minecraft server, the cooking pot is working well.
It's probably a bad interaction issue with another mod, so I can't help you without the mods list.

I can't suggest you to disable mods four by four (if you have a lot) and try to understand like that what mod interact and cause the cooking pot not working.

**Comment by ConqAra** [comment]
I'm having this problem with 1.18.2 version, here's the [modlist](https://paste.ee/p/pnkWt)
