### ISSUE TITLE
[Bug] no straw when harvesting adult rice plant with knife.

### ISSUE THREAD

**Issue by FyzerVR** [newhoryzon/farmers-delight-fabric#57]
Issue on Version 1.2.0 - 1.18.2 Fabric:

Fully grown rice crops are not dropping the additional 1 Straw when cut with the knife (the expected 1 rice is dropping however). Wheat is still behaving normally and dropping wheat, seeds, and straw when cut with the knife.

To verify that the behavior is still present in the latest forge edition of farmers delight on 1.18.2 I spun up a instance with just farmers and forge installed. Testing did show that harvesting adult rice plant with a knife will drop the expected 1 rice and 1 straw.

**Comment by Zifiv** [comment]
Hello @FyzerVR, thanks for reporting this issue, it will be fixed soon !
