### ISSUE TITLE
Skillet cannot be enchanted with a book of enchantment

### ISSUE THREAD

**Issue by PKalyps0** [newhoryzon/farmers-delight-fabric#65]
Hi,

I can't seem to enchant skillets using books of enchantment. They enchant fine on an enchantment table, and the forge version devs indicated this issue doesn't exist in their version. 

I'm on fabric version 0.14.8 on Minecraft 1.19 with FD fabric 1.3.2

**Comment by Ahlixemus** [comment]
This issue also extends to Knives. I can't add a Sharpness V book onto a Netherite Knife in an anvil. This only happens in Survival and not Creative mode.
