### ISSUE TITLE
Several missing JEI recipes

### ISSUE THREAD

**Issue by cybercat5555** [newhoryzon/farmers-delight-fabric#66]
Several items, such as Stuffed Pumpkins and Veggie Soup, do not have their recipes show up in JEI

If I had to guess, it seems the cooking and cutting recipes were not ported fully/were broke in the process.

Fabric 1.19.2
Farmer's Delight 1.3.3

**Comment by JieningYu** [comment]
Please use REI with Farmer's Delights Fabric.

**Comment by Zifiv** [comment]
Hello @cybercat5555,

Like @JieningYu said, Farmer's Delight fabric isn't compatible with JEI, you should use REI.
