### ISSUE TITLE
Farmer's Delight Invalid key error spam

### ISSUE THREAD

**Issue by Skeithh** [newhoryzon/farmers-delight-fabric#70]
Each time I interact with any farmer's delight object my logs spam 

```
########## GL ERROR ##########
@ Render
65539: Invalid key -1
```

Using farmer's delight 0.2.1 for 1.18.2 on fabric 0.14.9

**Comment by Zifiv** [comment]
Hello @Skeithh, you can upgrade the version of Farmer's Delight Fabric to 1.2.1 (the latest available for 1.18.2).

**Comment by Skeithh** [comment]
Oh, I see! We'll update and see if that fixes it and will report back otherwise ^^

**Comment by Skeithh** [comment]
Hey, we updated and the issue still persists :(
