### ISSUE TITLE
Problem with a custom recipe and use of tags

### ISSUE THREAD

**Issue by Abalieno** [newhoryzon/farmers-delight-fabric#71]
I was trying to define the cutting board recipes to use a tag as ingredient rather than a item.

So for example a recipe that would accept all log types as "tag": "minecraft:logs"

This actually works in game, I've tested it.

The problem is that KubeJS errors when I first log into the world. The recipe loads and works after I do a second /reload

It gives an error the first time:

[WARN ] Error creating recipe farmersdelight:cutting[farmersdelight:cutting]: {"type":"farmersdelight:cutting","ingredients":[{"tag":"minecraft:logs"}],"tool":{"type":"farmersdelight:tool","tag":"c:tools/axes"},"result":[{"item":"geggy:j_stripped_log"},{"item":"farmersdelight:tree_bark"}],"sound":"minecraft:item.axe.strip"}: com.google.gson.JsonParseException: No ingredients for cooking recipe

If I replace the tag item, with an actual specific item, then it loads fine even the first time.

I guess there's a reason why farmer's delight default recipes don't debark all wood types, but have one individual recipe for every type of standard Minecraft wood.

It would work better if it accepted all wood types, but I guess the mod can't properly deal with tags?

**Comment by Abalieno** [comment]
![weerdc](https://user-images.githubusercontent.com/4656436/193505598-d958c02b-526a-4368-848c-568f742e4a3f.jpg)

Got this workaround working fine, after tons of help.

This deals with most wood types, outside of modded ones that don't set #c:stripped_logs

**Comment by Zifiv** [comment]
Hello @Abalieno,

It seems that isn't an error in Farmer's Delight plus you seems to found a fix for your problem with KubeJS.

Then I close the issue, feel free to tell me if you think something need to be updated in Farmer's Delight fabric.
