### ISSUE TITLE
1.19.2 bug signs don't have their own GUI

### ISSUE THREAD

**Issue by MrJorman** [newhoryzon/farmers-delight-fabric#74]
When I put a sign from the Farmer's Delight mod and try to write on it, I don't see the GUI of the sign)) I'm writing in the void and I can't see the letters)

**Comment by MrJorman** [comment]
Fix pls.!

**Comment by Zifiv** [comment]
Hello @MrJorman,

Did you try without any other mods ?
Because I've not issue with the GUI with only Farmer's Delight installed.
