### ISSUE TITLE
[SUGGESTION] Sweet berry crates?

### ISSUE THREAD

**Issue by BowBoy1** [newhoryzon/farmers-delight-fabric#75]
Many of the other crops have crop crates added by this mod, maybe add a sweet berry one at some point?

**Comment by JieningYu** [comment]
This is just a port of Farmer's Delight. Suggestions please go [here](https://github.com/vectorwing/FarmersDelight/issues)

**Comment by Zifiv** [comment]
Hello @BowBoy1,

Exactly as @JieningYu said, this is just the port fabric of original mod Farmer's Delight, my goal isn't to add things that are not present in the original forge version.
So if you have any suggestion you can follow the link suggested by @JieningYu.

Thank you.
