### ISSUE TITLE
1.18.2fabric1.2.1版本的染色粗布告示牌无法合成

### ISSUE THREAD

**Issue by HG-Ted** [newhoryzon/farmers-delight-fabric#76]
![image](https://user-images.githubusercontent.com/105895618/198860003-c4e44ea4-627c-43a3-8724-466cb84966d5.png)
![image](https://user-images.githubusercontent.com/105895618/198860005-62eebe7d-e9a6-4674-9313-9152e4e7c170.png)
合成配方确认过没有错，就是无法合成

**Comment by JieningYu** [comment]
请使用英语提交issue，配方请以REI中显示的为准。

**Comment by Zifiv** [comment]
Duplicate of #77.
