### ISSUE TITLE
1.18.2fabric 1.2.1 Dyed's coarse cloth Billboard cannot be synthesized

### ISSUE THREAD

**Issue by HG-Ted** [newhoryzon/farmers-delight-fabric#77]
![image](https://user-images.githubusercontent.com/105895618/198860104-18519aee-2f15-42a8-bbdd-a4f59f55dd47.png)
![image](https://user-images.githubusercontent.com/105895618/198860105-0b60a5b1-8129-4b12-a065-eb6b2727a8a6.png)
The composition is right

**Comment by JieningYu** [comment]
Use REI to check the recipe.
