### ISSUE TITLE
MathUtils infinite loop

### ISSUE THREAD

**Issue by brocksmith225** [newhoryzon/farmers-delight-fabric#81]
There is an infinite loop here caused by a misnamed variable:
https://github.com/newhoryzon/farmers-delight-fabric/blob/master/src/main/java/com/nhoryzon/mc/farmersdelight/util/MathUtils.java#L21

**Comment by Zifiv** [comment]
Deployed in 1.3.4 for MC1.19.X and in 1.2.2 for MC1.18.2 !
