### ISSUE TITLE
[1.19.3] Files marked 1.19.3 crash at start 

### ISSUE THREAD

**Issue by kwpugh** [newhoryzon/farmers-delight-fabric#86]
With the breaking changes to ItemGroup setting, 1.19.2 and 1.19.3 are not likely to be compatible.

crash report:   https://gist.github.com/kwpugh/25ac4803f715ef0963f91b95c53ee815

**Comment by Zifiv** [comment]
Hello @kwpugh,

Thank you for reporting the issue with 1.19.3, so it seems that passing to 1.19.3 need changes.
I mark it for next release 👍.

**Comment by kwpugh** [comment]
Keep in mind, from what I have seen in updating my mods to 1.19.3 is that 1.19.2 and 1.19.3 mods will NOT be compatible with each other because of the changes Mojang made to how itemgroups work.

They removed .group() from Item.Setting.  You now need to create your own ItemGroup class and add to vanilla or custom groups from there.

By way of example, here is how I am handling in my mods:
https://github.com/kwpugh/veggie_way_fabric/blob/22w43a/src/main/java/com/kwpugh/veggie_way/util/VeggieWayGroup.java

**Comment by 19Phin** [comment]
with all due respect, why isn't this done yet? it doesn't seem that difficult

**Comment by anxiousoracle** [comment]
I keep getting error code 255 when trying to run 1.19.3 on Fabric. Version 1.19.X-1.3.9 for Fabric keeps giving me the same issue. I can run it on 1.19.2 just fine, though.

**Comment by PixelDough** [comment]
I might look into this issue some time soon. That example @kwpugh gave seems really helpful!

**Comment by Zifiv** [comment]
> with all due respect, why isn't this done yet? it doesn't seem that difficult

Because there is not only the ItemGroup to be changed...

**Comment by Zifiv** [comment]
Release for Minecraft 1.19.4 and 1.20-1.20.1 has been uploaded (no plan for 1.19.3).
