### ISSUE TITLE
Broken Dumplings recipe

### ISSUE THREAD

**Issue by ClaudiusMinimus** [newhoryzon/farmers-delight-fabric#88]
A player for my new pack, [Create on a Potato PC: Fabric Edition](https://www.curseforge.com/minecraft/modpacks/create-on-a-potato-pc-fabric-edition) just reported on my discord how there is a duplicate and broken dumplings recipe in farmers-delight-fabric-1.18.2-1.2.2

![image](https://user-images.githubusercontent.com/17887664/199831723-81fc1490-82ed-4419-af19-21b4d6ebd939.png)

**Comment by Zifiv** [comment]
Hello @ClaudiusMinimus,

I've the same version installed in my custom datapack [HORYZONEA](https://www.curseforge.com/minecraft/modpacks/horyzonea) and there is only one cooking recipe for dumplings.

The mod that add the broken recipe is [CreatePlus](https://www.curseforge.com/minecraft/mc-mods/createplus), according to what his author said ([here](https://github.com/JieningYu/CreatePlus/issues/12#issuecomment-1255870179)), CreatePlus is abandoned and he's working on a new version that will be called CreatePlus Next.
