### ISSUE TITLE
Rich Soil Issue in Better MC [FABRIC] 1.19.2 V10

### ISSUE THREAD

**Issue by Bananente** [newhoryzon/farmers-delight-fabric#90]
Modpack uses farmers-delight-fabric-1.19.X-1.3.5 and i got the same issue like here: https://github.com/newhoryzon/farmers-delight-fabric/issues/30

**Comment by ryhnochaser09** [comment]
I got the same issue using Better MC [FABRIC] 1.19.2 ... can not plant seeds in Rich Soil.

**Comment by Zifiv** [comment]
This is an incompatibility with MoreTags mod, his author intentionaly break others mod to use the mixin for "canPlantOnTop" of PlantBlock, this is the mixin I use to make Rich Soil Farmland works as a farmland.
So for now, the modpack author, should know about this incompatibility and add default datapack to add Rich Soil Farmland in the tag added by MoreTags.
