### ISSUE TITLE
JEI should work with Cooking Pot recipes

### ISSUE THREAD

**Issue by TheThoughtsmith** [newhoryzon/farmers-delight-fabric#93]
Fabric versions of both JEI and Farmers Delight Fabric.
1.18.2

As the title states, JEI does not work with the cooking pot recipes. The crafting grid recipes for food work just fine though.

**Comment by JieningYu** [comment]
why don't use REI?

**Comment by Zifiv** [comment]
Farmer's Delight Fabric version have the REI integration, use it instead of JEI.
It's not planned to add integration for JEI for now.

**Comment by TheThoughtsmith** [comment]
Fair workaround. Good to know
